# Generated by Django 3.2.4 on 2021-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('stockname', models.CharField(max_length=50)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
